const IGDB_BASE_API_URL = process.env.REACT_APP_IGDB_BASE_API_URL;
const IGDB_BASE_URL = process.env.REACT_APP_IGDB_BASE_URL;
const TWITCH_AUTH_URL = process.env.REACT_APP_TWITCH_AUTH_URL;
const TWITCH_CLIENT_ID = process.env.REACT_APP_TWITCH_CLIENT_ID;
const TWITCH_CLIENT_SECRET = process.env.REACT_APP_TWITCH_CLIENT_SECRET;
const AWS_API_KEY = process.env.REACT_APP_AWS_API_KEY;

const TIME_OUT_SEC = 10000;

export {
	IGDB_BASE_API_URL,
	IGDB_BASE_URL,
	TWITCH_AUTH_URL,
	TWITCH_CLIENT_ID,
	TWITCH_CLIENT_SECRET,
	AWS_API_KEY,
	TIME_OUT_SEC,
};
