const TMDB_BASE_URL = process.env.REACT_APP_TMDB_BASE_URL;
const TMDB_IMAGE_URL = process.env.REACT_APP_TMDB_IMAGE_URL;
const TMDB_API_KEY = process.env.REACT_APP_TMDB_API_KEY;

const TIME_OUT_SEC = 10000;

export { TMDB_BASE_URL, TMDB_IMAGE_URL, TMDB_API_KEY, TIME_OUT_SEC };
